# Generated by Django 5.2.7 on 2025-11-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dept', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
